"use strict";
let nama = 'Putra wiranata';
let nim = 160030071;
let bebas = "penggnaan";
let bebasTerprediksi;
let arrayString;
bebas += 123;
bebasTerprediksi = 123;
arrayString = ["testing", "testing1"];
console.log({ nama });
console.log({ nim });
console.log({ bebas });
console.log({ arrayString });
